### ISSUE TITLE
Message class should have User foreign key

### ISSUE THREAD

**Issue by Jake-L** [cp317/analysis#16]
In the class_diagram.pdf file, there should be a way of linking a message to the user who sent it, that way when we display chat messages on a course/beacon page we can use that key to get their avatar image and possibly link to their profile.

**Comment by GarethSharpe** [comment]
I see, yes that makes sense. The **Message** class has an attribute named _username_ and the constructor now takes a message argument and a username argument. Great suggestions. Will be reflected by the end of the day.

**Comment by GarethSharpe** [comment]
Closed Issue #16
