### ISSUE TITLE
Message class constructor should be public

### ISSUE THREAD

**Issue by Jake-L** [cp317/analysis#17]
Should the Message class constructor should be public so that another class can instantiate it? Unless you intended it to be a private class that only the Chat class can access, but then the Chat class might need a new method to create a new Message object.

**Comment by GarethSharpe** [comment]
I was thinking that only a chat could create a message. That way the message is linked to a specific chat ID and as such a specific chat log that can be closed via the chat. But yes, I will need a new method to create a new message object. I can make it package access?

**Comment by Jake-L** [comment]
Okay that's what I was thinking as well. Yeah, I think package access would accomplish what we want.

**Comment by GarethSharpe** [comment]
Perfect. 
Closed Issue #17
