### ISSUE TITLE
Move User attributes to Registered User

### ISSUE THREAD

**Issue by Jake-L** [cp317/analysis#18]
The User class has too many attributes that should be in Registered User instead. An unregistered user shouldn't be able to store their school or bio, and I think without an email we wouldn't have their gravatar either. I don't remember having usernames before, but it is a good idea so we don't have to identify users by their email address in chats. However, an unregistered user would probably just show up as anonymous, so I can think we could move the username attribute to Registered User as well.

**Comment by Jake-L** [comment]
Also, the logout method should be moved to registered user as well.

**Comment by GarethSharpe** [comment]
Okay, all sounds good. Question about the chat/invite then. The username of a user (including a guest) is used for the chat feature as well as the invite feature. Should we keep the username in the User class so that any user (registered or not) can chat or be invited to a beacon?

**Comment by Jake-L** [comment]
What I was thinking is there is probably no way for anyone to find the profile of an unregistered user, so they would never get invited to any beacons. Extending my assumption that unregistered users don't have profile pages, it would also be impossible to anyone to start a conversation with an unregistered user. If a unregistered user participated in a public discussion on a course page or beacon page, they could just be shown as Anon1234 or something. I think we might need to have the broader discussion of  what unregistered users can do and whether or not they have profile pages, because that isn't something I want to decide myself. If we assign them temporary usernames and they can be invited to beacons, then I would definitely want them to have the ability to create their own beacons, which I know some people are against.

**Comment by GarethSharpe** [comment]
I kind of like the idea of a randomly generated username (that is fun) that can still be used to invite and chat etc. Perhaps I will keep the username in the generic **User** class and we can talk about how that will work next class?

**Comment by Jake-L** [comment]
Okay sounds good.
