### ISSUE TITLE
User should store current beacon

### ISSUE THREAD

**Issue by Jake-L** [cp317/analysis#19]
The user has an option to leave a beacon, which takes a beacon object as a parameter, but they don't store a beacon so they have nothing to pass as an argument. I think they should have an attribute where they store the beacon they are attending, which maybe should even be a list/array, since they could theoretically say they will be at one beacon at 1pm and another at 4pm (for example).

**Comment by GarethSharpe** [comment]
So here is what I was thinking with this, but you can tell me if I am way off. I was thinking that if a registered user is deciding to close a beacon, they are the ones selecting the beacon they would like to close. If they are selecting the beacon they would like to close, then that beacon object is already stored. If a _close_ button was available on the beacon page, then that beacon would be passed as an argument. Thoughts?

**Comment by Jake-L** [comment]
I was thinking from the perspective of a user who initially joins one beacon, then changes their mind and joins a different one for the same time. But if we make them leave the first beacon before joining the second, then they would click leave and we could get that beacon as a parameter, so yeah you're right.

**Comment by GarethSharpe** [comment]
I LOVE BEING RIGHT. Okay good stuff. Thanks for your help. 
Closed #19
