### ISSUE TITLE
Multiplicities

### ISSUE THREAD

**Issue by Amandeep-G** [cp317/analysis#20]
- For registered users you indicated that they can be linked to 1..n beacons, I think that should be 0..n because they don't necessarily have to be hosting a beacon at all times. For example a new user would not be linked to any beacons upon creation, or a user could have all their hosted beacons expired.

- Courses should be linked to 0..n users because a course could have 0 users if it was just added into the system or after a course is done, all users would leave the course and new new users could have joined it

**Comment by GarethSharpe** [comment]
Great suggestions @Amandeep-G .
- multiplicity for beacons changed to 0..*
- question about this suggestion. Should the multiplicity for both then be 0..* considering that a course could have no users & a user could have no courses?

**Comment by Amandeep-G** [comment]
The multiplicity for users to courses is already showing 0..* for me, so now they should both be 0..*

**Comment by GarethSharpe** [comment]
Perfect. Suggestions will be made visible when I upload the next version. Thanks a lot for your help.
