### ISSUE TITLE
use_case_diagram needed changes.

### ISSUE THREAD

**Issue by MilikSmith76** [cp317/analysis#22]
- All use of "beacon" should be changed to "Beacon" to stay consistence with the rest of the documents.
- The first letter of each use case should be capitalized. 
- "Guest" Should be change to "Guest User" as the guest is referred to as Guest User in other documents.

**Comment by GarethSharpe** [comment]
- All use of "beacon" now "Beacon"
- First letters capitalized
- Guest was already "Guest User" (might have made this change right before you SQA'd)

Thanks for your help.
Closed Issue #22
