### ISSUE TITLE
sequence_diagram needed changes.

### ISSUE THREAD

**Issue by MilikSmith76** [cp317/analysis#25]
- “Geust” should be "Guest" at the top.
- (2) login Button should be all lower case.
- (4) “registered user” should be changed to “Registered User”.
- (5) “login” should be changed to “Login”.
- (6) “beacon” should be changed to “Beacon”.
- (9) “join” should be changed to “Join”, “geust” should be changed to "Guest".
- (14) Change “chat” to “Chat”.
- (15) Change “create” to “Create”.
- (16) Change “chat” to “Chat”.

**Comment by garrettparris** [comment]
changed sequence diagrams
