### ISSUE TITLE
Some Class_Diagram changes

### ISSUE THREAD

**Issue by MilikSmith76** [cp317/analysis#29]
- “string” Attributes should be “String” Attributes. JavaScript has String objects not string objects.
- “date” Attributes should be “Date” Attributes. JavaScript has Date objects not date objects.
- All attribute should be private (ex. Look at "school" Attribute in Course class).
- All methods should start with a capital letter as described in the standards document.
- In User class constructor, the parameter "username" should be "userName".
- In Course class, shouldn't the "description" parameter for the class constructor should be String description = None?
- In Beacon class constructor, "Host host" parameter should be replaced with "RegisteredUser host". There is no Host object.
- In Beacon class, “member” Attribute being a string[] makes the class tightly coupled.
- In Message class constructor, the parameter "username" should be "userName".
- In Message class, doesn't "userName" Attribute being a string make it tightly coupled?
- Shouldn't "chatLog" Attribute in Chat class be a String Attribute?

**Comment by GarethSharpe** [comment]
Awesome, thanks for the SQA. I implemented all of these except the suggestion to make the chatLog attribute a String attribute. When talking with DB he said that the individual messages themselves (msgString) would be the string elements that would be appended to the chatLog via a method within the Chat class. 

> In Message class, doesn't "userName" Attribute being a string make it tightly coupled?

Yes it does so I changed it to sender: User. The sender attribute now holds an actual user as opposed to a user name.
