### ISSUE TITLE
Some Sequence Diagrams changes

### ISSUE THREAD

**Issue by MilikSmith76** [cp317/analysis#30]
Sequence_Logout:
- 3 is returned to nothing? (I'm not sure if this is an actual issue).

Sequence_EditProfile:
- 5's description should have it's first letter capitalized.

Sequence_BeaconLeave:
- 4 is returned to nothing? (I'm not sure if this is an actual issue).

Sequence_BeaconInvite:
- 3, in description “beacon” should be “Beacon”.

Sequence_BeaconCreation:
- 2's description should start with a capital letter.

Sequence_BeaconClose:
- 3's description should start with a capital letter.

**Comment by garrettparris** [comment]
fixed
