### ISSUE TITLE
Some AnalysisDoc changes

### ISSUE THREAD

**Issue by MilikSmith76** [cp317/analysis#31]
Section 1:
- paragraph 1, sentence 1: Why is the app called "Study Group Finder" not "Study Space"?
- paragraph 1, sentence 2: This is in future tense, should be in present tense.

Section 2:
- For all entity objects, boundary objects, and control objects the description should start with a capital letter and end in a period, as done in the Requirements document.

Section 2.1:
- Change “Guest” entity to “Guest User” and in the description replace “person” with “User”.
- Change “User” entity's description to something like “A person how is using this application.”, and add a “Registered User” entity with the current description of “User” but replace “person” with “User”.
- Remove “Host” entity (it is not used anywhere in diagrams).
- In “Profile” entity description replace “User” with "Register User".
- Change the Beacon entity's description to something like “A study location and the details of that study group created by a Registered User that Users may join.”.
- In “ChatDB” entity's description “users” should be “Users”.
- Missing “UserDB” entity object.

Section 2.2:
- The first four Boundary objects are not in alphabetical order.
- All instances of “beacon” in descriptions should be changed to “Beacon”.
- All instances of “user” in descriptions should be changed to “User”.
- All instances of “profile” in descriptions should be changed to “Profile”.
- All instances of "Host" in descriptions should be changed to "host".
- In the description for "BeaconCreationWindow", "User" should be replaced for "Registered User".
- Remove “and Guests” in the description for “BeaconChatWindow” object.
- Be more clear for description of “FilterBeaconWindow” object.
- Remove “and Guests” in the description for “HomeWindow” object.
- Missing “ProfileEditWindow” boundary object.
- Remove “EditProfileView”, and “FilterBeaconView” as they don't exist.

Section 2.3:
- All instance of “Host” should be change to “host”.
- All instances of “beacon” in descriptions should be changed to “Beacon”.
- All instances of “user” in descriptions should be changed to “User”.
- All instances of “profile” in descriptions should be changed to “Profile”.
- In description of “ApplySearchFilters” object, “beaconlist” should be “BeaconList”.
- In description of “BackToSearch” object, “searchwindow” should be “SearchWindow”.
- Missing “LeaveBeacon”, and “EditProfile” control object.
- Remove “ChangeToHost”, “ProfileSearch”, “NotifyUser” as they do not exist.

Section 3:
- There should be a newline separating the starting of section 3 and the ending of section 2.
- Some of the diagrams are out of date. (I don't think it really matters for this document at the moment).

**Comment by garrettparris** [comment]
edited the errors

**Comment by MilikSmith76** [comment]
The version seem great except:
- “UserDB” entity placement breaks alphabetical order in section 2.1.
- In entity, boundary and control object descriptions “chat” should probably be “Chat”.
- In the Class Diagram Description's opening paragraph “diagrams” should be “diagram”.
- In Chat description “chat” should be “Chat”.
- In Message description, “constructor” is spelled as “constructer”.
- In Message description, “chat” should be “Chat”.

**Comment by garrettparris** [comment]
updated
