### ISSUE TITLE
Some methods should be private

### ISSUE THREAD

**Issue by chhomchhom** [cp317/analysis#7]
Chat
(-) ID: so other users or programmers can't mess with this
(-) getID: other programmers don't need access to ID of the chat

Beacon
all global variables should be privatized to prevent privacy leaks 
(-) getID

Host
i think some of the methods should be private but I'm not too sure

**Comment by GarethSharpe** [comment]
Implemented suggested changes. Will be reflected in new diagram this evening. 
Thanks a lot.
